----------------------------------------------------------------------------------------------------------------------------------------
-- CREATE WAREHOUSES
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS DBT_LEATHER_SHOP_DEV_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;
CREATE WAREHOUSE IF NOT EXISTS DBT_DBT_LEATHER_SHOP_PRD_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;

CREATE WAREHOUSE IF NOT EXISTS _ORCHESTRATION_DEV_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;
CREATE WAREHOUSE IF NOT EXISTS _ORCHESTRATION_PRD_WH WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE AUTO_SUSPEND=60;

-------------------------------------------------------------------------------------------------------------------------------------------
---- CREATE ROLES:
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;
CREATE ROLE IF NOT EXISTS DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE;
--
CREATE ROLE IF NOT EXISTS DATA_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE;
CREATE ROLE IF NOT EXISTS DATA_ARCHITECT_ROLE;

USE ROLE SYSADMIN;
GRANT ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE TO ROLE SYSADMIN;

GRANT ROLE DATA_ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER_ROLE TO ROLE SYSADMIN;
GRANT ROLE DATA_ARCHITECT_ROLE TO ROLE SYSADMIN;

-- ROLE HIERACHY
GRANT ROLE DATA_ANALYST_ROLE TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE DATA_ENGINEER_ROLE TO ROLE DATA_ARCHITECT_ROLE;
----------------------------------------------------------------------------------------------------------------------------------------
---- CREATE SERVICE ACCOUNT USERS:
USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_USER
    PASSWORD = 'your_dev_password'
    COMMENT= 'Service account for dbt in the development (DEV) environment of the CCLAVE project.'
    DEFAULT_WAREHOUSE = DBT_DBT_DBT_DBT_DBT_DBT_DBT_DBT_DBT_LEATHER_SHOP_DEV_WH
    DEFAULT_ROLE= DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE
    MUST_CHANGE_PASSWORD=FALSE;
    
CREATE USER IF NOT EXISTS DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_USER
    PASSWORD = 'your_prd_password'
    COMMENT= 'Service account for dbt in the production (PRD) environment of the CCLAVE project.'
    DEFAULT_WAREHOUSE = DBT_LEATHER_SHOP_PRD_WH
    DEFAULT_ROLE= DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE
    MUST_CHANGE_PASSWORD=FALSE;


------------------------------------------------------------------------------------------------------------------------------------------
-- CEATE HUMAN USERS
CREATE USER IF NOT EXISTS DATA_ANALYST_USER1
    PASSWORD = 'analystPassword1!'
    DEFAULT_ROLE = DATA_ANALYST_ROLE
    MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS DATA_ENGINEER_USER1
    PASSWORD = 'engineerPassword1!'
    DEFAULT_ROLE = DATA_ENGINEER_ROLE
    MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS DATA_ARCHITECT_USER1
    PASSWORD = 'architectPassword123!'
    DEFAULT_ROLE = DATA_ARCHITECT_ROLE
    MUST_CHANGE_PASSWORD = FALSE;

    
---------------------------------------------------------------------------------------------------------------------------------------
---- GRANT ROLES TO USERS
USE ROLE USERADMIN;
-- SERVICE ACCOUNT USERS
GRANT ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE TO USER DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_USER;
GRANT ROLE DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE TO USER DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_USER;
-- HUMAN USERS
GRANT ROLE DATA_ANALYST_ROLE TO USER DATA_ANALYST_USER1;
GRANT ROLE DATA_ENGINEER_ROLE TO USER DATA_ENGINEER_USER1;
GRANT ROLE DATA_ARCHITECT_ROLE TO USER DATA_ARCHITECT_USER1;
-- SO THAT DATA ENGINEERS CAN EASILY ACCESS THE DATA CREATE BY DBT IN DEV
GRANT ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE TO ROLE DATA_ENGINEER_ROLE;

-------------------------------------------------------------------------------------------------------------------------------------------
---- CREATE OBJECTS
USE ROLE SYSADMIN;
---- DATABASES
CREATE DATABASE IF NOT EXISTS LEATHER_SHOP_DEV;
CREATE DATABASE IF NOT EXISTS LEATHER_SHOP_PRD;

CREATE DATABASE IF NOT EXISTS RAW_DEV;
CREATE DATABASE IF NOT EXISTS RAW_PRD;

-- SCHEMAS
CREATE SCHEMA IF NOT EXISTS RAW_DEV._ORCHESTRATION;
CREATE SCHEMA IF NOT EXISTS RAW_PRD._ORCHESTRATION;

CREATE SCHEMA IF NOT EXISTS RAW_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS RAW_PRD.RAW;


-------------------------------------------------------------------------------------------------------------------------------------------
---- GRANT PRIVILEGES for DBT SERVICE ACCOUNTS:
USE ROLE SECURITYADMIN;
-----
-- FOR DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE
GRANT USAGE ON WAREHOUSE DBT_LEATHER_SHOP_DEV_WH TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;
-- RAW DATA ACCESS
GRANT USAGE ON DATABASE LEATHER_SHOP_DEV TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;
GRANT USAGE ON SCHEMA RAW_DEV.RAW TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_DEV.RAW TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;
-- FUTURE DATA ACCESS
GRANT CREATE SCHEMA ON DATABASE LEATHER_SHOP_DEV TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON FUTURE SCHEMAS IN DATABASE LEATHER_SHOP_DEV TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;

-----------------------------
-- FOR DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE
GRANT USAGE ON WAREHOUSE DBT_LEATHER_SHOP_PRD_WH TO ROLE DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE;
-- RAW DATA ACCESS
GRANT USAGE ON DATABASE LEATHER_SHOP_PRD TO ROLE DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE;
GRANT USAGE ON SCHEMA RAW_PRD.RAW TO ROLE DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_PRD.RAW TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;
-- FUTURE DATA ACCESS
GRANT CREATE SCHEMA ON DATABASE LEATHER_SHOP_DEV TO ROLE DBT_LEATHER_SHOP_PRD_SERVICE_ACCOUNT_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON FUTURE SCHEMAS IN DATABASE LEATHER_SHOP_PRD TO ROLE DBT_LEATHER_SHOP_DEV_SERVICE_ACCOUNT_ROLE;


-------------------------------------------------------------------------------------------------------------------------------------------
---- GRANT PRIVILEGES for HUMAN USERs ROLES:
-- ANALYST
GRANT USAGE ON DATABASE LEATHER_SHOP_PRD TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LEATHER_SHOP_PRD TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE LEATHER_SHOP_PRD TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE DBT_LEATHER_SHOP_PRD_WH TO ROLE DATA_ANALYST_ROLE;

-- ENGINEER
GRANT USAGE ON DATABASE LEATHER_SHOP_DEV, LEATHER_SHOP_PRD, RAW_DEV, RAW_PRD TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LEATHER_SHOP_DEV TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DEV TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE LEATHER_SHOP_DEV TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE RAW_DEV TO ROLE DATA_ENGINEER_ROLE;

-- ARCHITECT
USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DATA_ARCHITECT_ROLE;
GRANT CREATE SCHEMA ON ACCOUNT TO ROLE DATA_ARCHITECT_ROLE;

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE _ORCHESTRATION_DEV_WH TO ROLE DATA_ARCHITECT_ROLE;
GRANT USAGE ON WAREHOUSE _ORCHESTRATION_PRD_WH TO ROLE DATA_ARCHITECT_ROLE;